<a href="https://colab.research.google.com/github/RudolfVonStroheim/RaceClassifier/blob/main/Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
!pip install pandas-plink
!curl -O http://www.russiangenome.ru/biengi.zip
!unzip biengi.zip -d biengi
!wget http://s3.amazonaws.com/plink1-assets/plink_linux_x86_64_20200121.zip -O plink.zip
!unzip -q -n plink.zip plink

Requirement already satisfied: pandas-plink in /usr/local/lib/python3.12/dist-packages (2.3.2)
Requirement already satisfied: cffi>=1.17 in /usr/local/lib/python3.12/dist-packages (from pandas-plink) (2.0.0)
Requirement already satisfied: dask[dataframe] in /usr/local/lib/python3.12/dist-packages (from pandas-plink) (2026.3.0)
Requirement already satisfied: deprecated<2.0,>=1.2 in /usr/local/lib/python3.12/dist-packages (from pandas-plink) (1.3.1)
Requirement already satisfied: numpy<2.0,>=1.0 in /usr/local/lib/python3.12/dist-packages (from pandas-plink) (1.26.4)
Requirement already satisfied: pandas<3.0,>=2.2 in /usr/local/lib/python3.12/dist-packages (from pandas-plink) (2.2.2)
Requirement already satisfied: pandera[dask,mypy] in /usr/local/lib/python3.12/dist-packages (from pandas-plink) (0.31.1)
Requirement already satisfied: tqdm<5.0,>=4.67 in /usr/local/lib/python3.12/dist-packages (from pandas-plink) (4.67.3)
Requirement already satisfied: xarray in /usr/local/lib/python3.12/dist-packages (from pandas-plink) (2025.12.0)
Requirement already satisfied: zstandard<0.24,>=0.23 in /usr/local/lib/python3.12/dist-packages (from pandas-plink) (0.23.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.17->pandas-plink) (3.0)
Requirement already satisfied: wrapt<3,>=1.10 in /usr/local/lib/python3.12/dist-packages (from deprecated<2.0,>=1.2->pandas-plink) (2.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=2.2->pandas-plink) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=2.2->pandas-plink) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=2.2->pandas-plink) (2026.2)
Requirement already satisfied: click>=8.1 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]->pandas-plink) (8.4.0)
Requirement already satisfied: cloudpickle>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]->pandas-plink) (3.1.2)
Requirement already satisfied: fsspec>=2021.09.0 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]->pandas-plink) (2025.3.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]->pandas-plink) (26.2)
Requirement already satisfied: partd>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]->pandas-plink) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]->pandas-plink) (6.0.3)
Requirement already satisfied: toolz>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]->pandas-plink) (0.12.1)
Requirement already satisfied: pyarrow>=16.0 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]->pandas-plink) (18.1.0)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (from pandera[dask,mypy]->pandas-plink) (2.12.3)
Requirement already satisfied: typeguard in /usr/local/lib/python3.12/dist-packages (from pandera[dask,mypy]->pandas-plink) (4.5.2)
Requirement already satisfied: typing_extensions in /usr/local/lib/python3.12/dist-packages (from pandera[dask,mypy]->pandas-plink) (4.15.0)
Requirement already satisfied: typing_inspect>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pandera[dask,mypy]->pandas-plink) (0.9.0)
Requirement already satisfied: pandas-stubs in /usr/local/lib/python3.12/dist-packages (from pandera[dask,mypy]->pandas-plink) (2.2.2.240909)
Requirement already satisfied: scipy-stubs in /usr/local/lib/python3.12/dist-packages (from pandera[dask,mypy]->pandas-plink) (1.17.1.5)
Requirement already satisfied: distributed in /usr/local/lib/python3.12/dist-packages (from pandera[dask,mypy]->pandas-plink) (2026.3.0)
Requirement already satisfied: locket in /usr/local/lib/python3.12/dist-packages (from partd>=1.4.0->dask[dataframe]->pandas-plink) (1.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3.0,>=2.2->pandas-plink) (1.17.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from typing_inspect>=0.6.0->pandera[dask,mypy]->pandas-plink) (1.1.0)
Requirement already satisfied: jinja2>=2.10.3 in /usr/local/lib/python3.12/dist-packages (from distributed->pandera[dask,mypy]->pandas-plink) (3.1.6)
Requirement already satisfied: msgpack>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from distributed->pandera[dask,mypy]->pandas-plink) (1.1.2)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from distributed->pandera[dask,mypy]->pandas-plink) (5.9.5)
Requirement already satisfied: sortedcontainers>=2.0.5 in /usr/local/lib/python3.12/dist-packages (from distributed->pandera[dask,mypy]->pandas-plink) (2.4.0)
Requirement already satisfied: tblib!=3.2.0,!=3.2.1,>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from distributed->pandera[dask,mypy]->pandas-plink) (3.2.2)
Requirement already satisfied: tornado>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from distributed->pandera[dask,mypy]->pandas-plink) (6.5.1)
Requirement already satisfied: urllib3>=1.26.5 in /usr/local/lib/python3.12/dist-packages (from distributed->pandera[dask,mypy]->pandas-plink) (2.5.0)
Requirement already satisfied: zict>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from distributed->pandera[dask,mypy]->pandas-plink) (3.0.0)
Requirement already satisfied: types-pytz>=2022.1.1 in /usr/local/lib/python3.12/dist-packages (from pandas-stubs->pandera[dask,mypy]->pandas-plink) (2026.2.0.20260518)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic->pandera[dask,mypy]->pandas-plink) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic->pandera[dask,mypy]->pandas-plink) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic->pandera[dask,mypy]->pandas-plink) (0.4.2)
Requirement already satisfied: optype<0.18,>=0.14.0 in /usr/local/lib/python3.12/dist-packages (from optype[numpy]<0.18,>=0.14.0->scipy-stubs->pandera[dask,mypy]->pandas-plink) (0.17.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.10.3->distributed->pandera[dask,mypy]->pandas-plink) (3.0.3)
Requirement already satisfied: numpy-typing-compat<20251207,>=20250818.1.25 in /usr/local/lib/python3.12/dist-packages (from optype[numpy]<0.18,>=0.14.0->scipy-stubs->pandera[dask,mypy]->pandas-plink) (20251206.1.25)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 33.0M  100 33.0M    0     0  7160k      0  0:00:04  0:00:04 --:--:-- 7161k
Archive:  biengi.zip
replace biengi/biengi.bed? [y]es, [n]o, [A]ll, [N]one, [r]ename: Т
error:  invalid response [Т]
replace biengi/biengi.bed? [y]es, [n]o, [A]ll, [N]one, [r]ename: N
--2026-05-31 10:59:49--  http://s3.amazonaws.com/plink1-assets/plink_linux_x86_64_20200121.zip
Resolving s3.amazonaws.com (s3.amazonaws.com)... 16.15.212.67, 16.15.183.67, 16.182.96.208, ...
Connecting to s3.amazonaws.com (s3.amazonaws.com)|16.15.212.67|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8916292 (8.5M) [application/zip]
Saving to: ‘plink.zip’

plink.zip           100%[===================>]   8.50M  10.9MB/s    in 0.8s

2026-05-31 10:59:50 (10.9 MB/s) - ‘plink.zip’ saved [8916292/8916292]

In [10]:
!mkdir pruned
!./plink --bfile biengi/biengi --indep 50 5 2 --out biengi/biengi_pruned # Прунинг датасета(мажно сделать средствами python, но так занимает меньше времени)
!./plink --bfile biengi/biengi --extract biengi/biengi_pruned.prune.in --make-bed --out pruned/data_pruned

mkdir: cannot create directory ‘pruned’: File exists
PLINK v1.90b6.15 64-bit (21 Jan 2020)          www.cog-genomics.org/plink/1.9/
(C) 2005-2020 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to biengi/biengi_pruned.log.
Options in effect:
  --bfile biengi/biengi
  --indep 50 5 2
  --out biengi/biengi_pruned

12975 MB RAM detected; reserving 6487 MB for main workspace.
242180 variants loaded from .bim file.
894 people (574 males, 320 females) loaded from .fam.
Using 1 thread (no multithreaded calculations invoked).
Before main variant filters, 894 founders and 0 nonfounders present.
Calculating allele frequencies... 0%1%2%3%4%5%6%7%8%9%10%11%12%13%14%15%16%17%18%19%20%21%22%23%24%25%26%27%28%29%30%31%32%33%34%35%36%37%38%39%40%41%42%43%44%45%46%47%48%49%50%51%52%53%54%55%56%57%58%59%60%61%62%63%64%65%66%67%68%69%70%71%72%73%74%75%76%77%78%79%80%81%82%83%84%85%86%87%88%89%90%91%92%93%94%95%96%97%98%99% done.
Total genotyping rate is 0.999006.
242180 variants and 894 people pass filters and QC.
Note: No phenotypes present.
Pruned 11016 variants from chromosome 1, leaving 7756.
Pruned 12295 variants from chromosome 2, leaving 7690.
Pruned 10287 variants from chromosome 3, leaving 6558.
Pruned 8308 variants from chromosome 4, leaving 5886.
Pruned 8936 variants from chromosome 5, leaving 5958.
Pruned 10102 variants from chromosome 6, leaving 6066.
Pruned 7678 variants from chromosome 7, leaving 5310.
Pruned 8991 variants from chromosome 8, leaving 5198.
Pruned 7716 variants from chromosome 9, leaving 4802.
Pruned 7463 variants from chromosome 10, leaving 5083.
Pruned 6993 variants from chromosome 11, leaving 4682.
Pruned 6956 variants from chromosome 12, leaving 4845.
Pruned 5027 variants from chromosome 13, leaving 3626.
Pruned 4465 variants from chromosome 14, leaving 3370.
Pruned 4087 variants from chromosome 15, leaving 3054.
Pruned 3944 variants from chromosome 16, leaving 3377.
Pruned 3609 variants from chromosome 17, leaving 3146.
Pruned 4772 variants from chromosome 18, leaving 3350.
Pruned 2323 variants from chromosome 19, leaving 2428.
Pruned 3448 variants from chromosome 20, leaving 2857.
Pruned 2571 variants from chromosome 21, leaving 1722.
Pruned 2591 variants from chromosome 22, leaving 1838.
Pruning complete.  143578 of 242180 variants removed.
Marker lists written to biengi/biengi_pruned.prune.in and
biengi/biengi_pruned.prune.out .
PLINK v1.90b6.15 64-bit (21 Jan 2020)          www.cog-genomics.org/plink/1.9/
(C) 2005-2020 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to pruned/data_pruned.log.
Options in effect:
  --bfile biengi/biengi
  --extract biengi/biengi_pruned.prune.in
  --make-bed
  --out pruned/data_pruned

12975 MB RAM detected; reserving 6487 MB for main workspace.
242180 variants loaded from .bim file.
894 people (574 males, 320 females) loaded from .fam.
--extract: 98602 variants remaining.
Using 1 thread (no multithreaded calculations invoked).
Before main variant filters, 894 founders and 0 nonfounders present.
Calculating allele frequencies... 0%1%2%3%4%5%6%7%8%9%10%11%12%13%14%15%16%17%18%19%20%21%22%23%24%25%26%27%28%29%30%31%32%33%34%35%36%37%38%39%40%41%42%43%44%45%46%47%48%49%50%51%52%53%54%55%56%57%58%59%60%61%62%63%64%65%66%67%68%69%70%71%72%73%74%75%76%77%78%79%80%81%82%83%84%85%86%87%88%89%90%91%92%93%94%95%96%97%98%99% done.
Total genotyping rate is 0.999034.
98602 variants and 894 people pass filters and QC.
Note: No phenotypes present.
--make-bed to pruned/data_pruned.bed + pruned/data_pruned.bim +
pruned/data_pruned.fam ... 0%1%2%3%4%5%6%7%8%9%10%11%12%13%14%15%16%17%18%19%20%21%22%23%24%25%26%27%28%29%30%31%32%33%34%35%36%37%38%39%40%41%42%43%44%45%46%47%48%49%50%51%52%53%54%55%56%57%58%59%60%61%62%63%64%65%66%67%68%69%70%71%72%73%74%75%76%77%78%79%80%81%82%83%84%85%86%87%88%89%90%91%92%93%94%95%96%97%98%99%done.

In [21]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from pandas_plink import read_plink
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.decomposition import PCA

In [20]:
# До прунинга
bim, fam, G = read_plink("biengi/biengi")
gn = pd.DataFrame(G.compute().T)
gn

Mapping files: 100%|██████████| 3/3 [00:00<00:00,  4.16it/s]

,0,1,2,3,4,5,6,7,8,9,...,242170,242171,242172,242173,242174,242175,242176,242177,242178,242179
0,1.0,2.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,...,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0
1,1.0,2.0,2.0,1.0,2.0,2.0,2.0,0.0,2.0,1.0,...,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0
2,2.0,1.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,...,2.0,1.0,1.0,1.0,1.0,2.0,0.0,2.0,2.0,2.0
3,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,1.0,...,0.0,2.0,2.0,2.0,2.0,2.0,1.0,0.0,1.0,1.0
4,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,...,2.0,0.0,0.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
889,1.0,2.0,0.0,2.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
890,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,0.0,...,2.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0
891,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,...,2.0,2.0,2.0,1.0,0.0,2.0,1.0,2.0,2.0,2.0
892,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,0.0,...,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0
893,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,0.0,...,2.0,2.0,2.0,1.0,0.0,2.0,1.0,2.0,2.0,2.0

In [19]:
#После прунинга
bim, fam, G = read_plink("pruned/data_pruned")
gn_p = pd.DataFrame(G.compute().T)
gn_p

Mapping files: 100%|██████████| 3/3 [00:00<00:00,  7.04it/s]

,0,1,2,3,4,5,6,7,8,9,...,98592,98593,98594,98595,98596,98597,98598,98599,98600,98601
0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,0.0,2.0,...,2.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,2.0
1,1.0,2.0,1.0,2.0,0.0,2.0,1.0,2.0,1.0,1.0,...,1.0,0.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0
2,2.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,...,0.0,1.0,2.0,2.0,1.0,1.0,2.0,0.0,2.0,2.0
3,2.0,2.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,...,1.0,0.0,2.0,0.0,2.0,2.0,2.0,1.0,0.0,1.0
4,1.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,...,1.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
889,1.0,2.0,2.0,0.0,1.0,1.0,1.0,2.0,1.0,1.0,...,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0
890,2.0,1.0,2.0,2.0,1.0,1.0,0.0,2.0,0.0,2.0,...,0.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0
891,2.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,...,2.0,2.0,2.0,2.0,1.0,0.0,2.0,1.0,2.0,2.0
892,2.0,1.0,2.0,2.0,2.0,2.0,0.0,2.0,0.0,2.0,...,2.0,0.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0
893,2.0,2.0,2.0,2.0,1.0,1.0,0.0,2.0,1.0,1.0,...,2.0,2.0,2.0,2.0,1.0,0.0,2.0,1.0,2.0,2.0

В результате LD-прунинга количество признаков удалось существенно сократить.
Необходимость данного метода обуславливается спецификой данных: в геноме большое количество блоков очень часто наследуются вместе и при обработке необходимо учитывать весь блок целиком, а не его фрагменты. В итоге число признаков сократилось чуть более, чем в два раза.

Принцип работы алгоритма: %пояснить за принцип работы%

/bin/bash: line 1: dc: command not found